### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by waahah** [Rock-Candy-Tea/hexo-circle-of-friends#100]
环境：github+sqlite+vercel+开启配置项友链SETTINGS_FRIENDS_LINKS，run workflow报下列错
地址：https://github.com/waahah/hexo-circle-of-friends

2023-04-20 01:05:26|ERROR|2078|hexo_circle_of_friends.utils.project|SYSTEM ERROR
Traceback (most recent call last):
  File "./hexo_circle_of_friends/run.py", line 152, in <module>
    main()
  File "./hexo_circle_of_friends/run.py", line 23, in main
    initsettings(settings, user_conf)
  File "./hexo_circle_of_friends/run.py", line 127, in initsettings
    settings_friends_json_read(json_api, user_conf)
  File "./hexo_circle_of_friends/run.py", line 89, in settings_friends_json_read
    if json_api.startswith("http"):
AttributeError: 'dict' object has no attribute 'startswith'
Error: Process completed with exit code 1.
![image](https://user-images.githubusercontent.com/90046731/233150195-abf807e9-5c75-41f6-983f-7576ea44be5d.png)

![image](https://user-images.githubusercontent.com/90046731/233151335-ac5007ea-965c-4b0b-bde6-57c915bbbdb2.png)

**Comment by hiltay** [comment]
这是配置api的地方，想直接写配置放到下面的`list`里。

**Comment by hiltay** [comment]
配置有问题，`LINK`可以置空，但不能没有`LINK`

**Comment by waahah** [comment]
额，LINK置空后再运行，github actons 还是显示获取文章为0，访问vercel域名/all显示{"message":"start error"}
开启的配置项友链都是支持atom.xml格式的，有什么问题吗？
![image](https://user-images.githubusercontent.com/90046731/233312914-e0c950d2-d104-4204-8e22-c05f0d185628.png)

**Comment by waahah** [comment]
请问哪里出错了

**Comment by hiltay** [comment]
正在排查，暂时先为`LINK`添加一条内容，应该可以解决。

**Comment by hiltay** [comment]
可以更新最新版本v6.0.0尝试

**Comment by waahah** [comment]
你好，这个问题当时在 [https://github.com/yyyzyyyz](https://github.com/yyyzyyyz) 排查之后解决了，忘记关闭issue了，谢谢
