### ISSUE TITLE
极简模式因range100个友链会显示message:error start抓取不到所以改成了10,终于可以爬取成功了，但在模型转换出现如下报错

### ISSUE THREAD

**Issue by ABCkillmen** [Rock-Candy-Tea/hexo-circle-of-friends#158]
插件版本：我拉取的最新
主题：stellar 1.29
hexo: 6.3.0
hexo-cli: 4.3.2
node: 18.20.4

SYSTEM ERROR
Traceback (most recent call last):
  File "/home/runner/work/hexo-circle-of-friends/hexo-circle-of-friends/./hexo_circle_of_friends/utils/simple_mode_transform_json.py", line 23, in <module>
    transform()
  File "/home/runner/work/hexo-circle-of-friends/hexo-circle-of-friends/./hexo_circle_of_friends/utils/simple_mode_transform_json.py", line 16, in transform
    data = sqlapi.query_all(list_, rule="created")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/hexo-circle-of-friends/hexo-circle-of-friends/api_dependencies/sql/sqlapi.py", line 51, in query_all
    last_update_time = max(x["createAt"].strftime("%Y-%m-%d %H:%M:%S") for x in last_update_time)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/hexo-circle-of-friends/hexo-circle-of-friends/api_dependencies/sql/sqlapi.py", line 51, in <genexpr>
    last_update_time = max(x["createAt"].strftime("%Y-%m-%d %H:%M:%S") for x in last_update_time)
                           ~^^^^^^^^^^^^
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 54, in sqlalchemy.cyextension.resultproxy.BaseRow.__getitem__
TypeError: tuple indices must be integers or slices, not str

**Comment by ABCkillmen** [comment]
自动工作流输出地址：https://github.com/ABCkillmen/hexo-circle-of-friends/actions/runs/10306402477/job/28529434162

**Comment by Wangijun** [comment]
一样出现了这个问题

**Comment by hiltay** [comment]
可以更新最新版本`v6.0.0`尝试
