### ISSUE TITLE
This Serverless Function has crashed.

### ISSUE THREAD

**Issue by Gahotx** [Rock-Candy-Tea/hexo-circle-of-friends#32]
```py
[GET] /all
18:22:25:32
[ERROR] AttributeError: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 293, in vc_handler
    response = asgi_cycle(__vc_module.app, body)
  File "/var/task/vc__handler__python.py", line 204, in __call__
    loop.run_until_complete(asgi_task)
  File "/var/lang/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/var/task/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/var/task/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/task/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/var/task/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/var/task/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/var/task/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/var/task/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/var/task/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/var/task/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/var/task/starlette/responses.py", line 136, in __call__
    await send(
  File "/var/task/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/var/task/starlette/middleware/errors.py", line 156, in _send
    await send(message)
  File "/var/task/vc__handler__python.py", line 232, in send
    self.on_request(headers, status_code)
  File "/var/task/vc__handler__python.py", line 253, in on_request
    self.response['headers'] = format_headers(headers, decode=True)
  File "/var/task/vc__handler__python.py", line 20, in format_headers
    key = key.decode()
    
[GET] /all?rule=created&start=0&end=20
18:22:11:63
[ERROR] AttributeError: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 293, in vc_handler
    response = asgi_cycle(__vc_module.app, body)
  File "/var/task/vc__handler__python.py", line 204, in __call__
    loop.run_until_complete(asgi_task)
  File "/var/lang/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/var/task/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/var/task/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/task/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/var/task/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/var/task/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/var/task/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/var/task/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/var/task/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/var/task/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/var/task/starlette/responses.py", line 136, in __call__
    await send(
  File "/var/task/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/var/task/starlette/middleware/errors.py", line 156, in _send
    await send(message)
  File "/var/task/vc__handler__python.py", line 232, in send
    self.on_request(headers, status_code)
  File "/var/task/vc__handler__python.py", line 253, in on_request
    self.response['headers'] = format_headers(headers, decode=True)
  File "/var/task/vc__handler__python.py", line 20, in format_headers
    key = key.decode()
```

**Comment by 2X-ercha** [comment]
这个问题具体排查了下，应该是sqlite跟vercel之间的部分中间依赖更改有关。leancloud和mysql貌似是没有这个问题的

**Comment by hiltay** [comment]
目测是vercel方面的问题，具体原因在排查中

**Comment by Gahotx** [comment]
刚刚从sqlite换回了leancloud部署，还是有问题
```py
[GET] /all?rule=created&start=0&end=20
11:26:38:90
[ERROR] Runtime.ImportModuleError: Unable to import module 'vc__handler__python': cannot import name 'safe_str_cmp' from 'werkzeug.security' (/var/task/werkzeug/security.py)
Traceback (most recent call last):

[GET] /all
11:26:10:36
[ERROR] Runtime.ImportModuleError: Unable to import module 'vc__handler__python': cannot import name 'safe_str_cmp' from 'werkzeug.security' (/var/task/werkzeug/security.py)
Traceback (most recent call last):
```

**Comment by hiltay** [comment]
事故原因确定了。Werkzeug在3.28日更新了新版本，将该函数弃用导致错误。see: https://stackoverflow.com/questions/71652965/importerror-cannot-import-name-safe-str-cmp-from-werkzeug-security
> Werkzeug released [v2.1.0](https://werkzeug.palletsprojects.com/en/2.1.x/changes/#version-2-1-0) today, removing 
> `werkzeug.security.safe_str_cmp.`

解决方案：
已经将本项目的Werkzeug版本lock在旧版本，目前vercel测试可以正常运行，请fetch本仓库到最新版本协助测试。
期待收到更多反馈。

**Comment by Gahotx** [comment]
> 事故原因确定了。Werkzeug在3.28日更新了新版本，将该函数弃用导致错误。see: https://stackoverflow.com/questions/71652965/importerror-cannot-import-name-safe-str-cmp-from-werkzeug-security
> 
> > Werkzeug released [v2.1.0](https://werkzeug.palletsprojects.com/en/2.1.x/changes/#version-2-1-0) today, removing
> > `werkzeug.security.safe_str_cmp.`
> 
> 解决方案： 已经将本项目的Werkzeug版本lock在旧版本，目前vercel测试可以正常运行，请fetch本仓库到最新版本协助测试。 期待收到更多反馈。

亲测有效\(^o^)/~
