### ISSUE TITLE
后端正常，前端报错

### ISSUE THREAD

**Issue by Cystee** [Rock-Candy-Tea/hexo-circle-of-friends#52]
博客链接：
https://www.casecori.top/circle/
仓库链接：
https://github.com/Cystee/hexo-circle-of-friends
API：
https://hexo-circle-of-friends-rosy.vercel.app/all

页面源码：

```markdown
---
title: 朋友圈
date: 2022-6-26
---

<div id="cf-container">与主机通讯中……</div>

<link rel="stylesheet" href="https://cdn.casecori.top/gh/lmm214/immmmm/themes/hello-friend/static/fcircle-beta.css">

<script type="text/javascript">
  var fdataUser = {
    apiurl: 'https://hexo-circle-of-friends-rosy.vercel.app/'
  }
</script>

<script type="text/javascript" src="https://cdn.casecori.top/gh/lmm214/immmmm/themes/hello-friend/static/fcircle-beta.js"></script>
```

控制台报错：

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'article_num')
    at loadStatistical (fcircle-beta.js:47:23)
    at fcircle-beta.js:265:7
```

**Comment by hiltay** [comment]
感谢反馈。
这是由于数据库文章数少于20篇导致的问题
初始时请求的url为：https://hexo-circle-of-friends-rosy.vercel.app/all?rule=created&start=0&end=20
在前端请求该链接时无法获取到信息，因此报错。

临时解决方案：再添加几个友链，让数据库的文章数量大于20
后续会修改这部分的逻辑，兼容文章小于20的情况，记得关注友链朋友圈的更新情况~

**Comment by hiltay** [comment]
4.3.3已修复
