### ISSUE TITLE
登录失败，vercel报错（`获取SECRET_KEY失败`）

### ISSUE THREAD

**Issue by YanDao0313** [Rock-Candy-Tea/hexo-circle-of-friends#81]
![image](https://user-images.githubusercontent.com/90099234/209627589-da94256d-a489-4af1-b003-bea937b204b4.png)  
> 控制台报错如下
> ![image](https://user-images.githubusercontent.com/90099234/209629469-e29d5f54-fcd9-4cac-b80a-3a583eadf38f.png)  

vercel执行时日志返回`获取SECRET_KEY失败，error_code:404`，清除缓存重新部署了也没有，前端除管理外，其余均正常  
前端进入设置时提示500错误（确认为部署后首次输入密码），地址在[我的博客](https://www.daoblog.top/fcircle/)，按照文档里的配置的、没有遗漏变量  

> ![image](https://user-images.githubusercontent.com/90099234/209628653-77ed79c9-b638-49e5-ad7b-b2761b99162d.png)  
> ![image](https://user-images.githubusercontent.com/90099234/209628731-bf2134e0-93ac-4817-927b-b86343cc84f1.png)  

部署环境：`github+sqlite+vercel (默认)`，修改域名为自定义的`https://cof-api.ydlk.cc/`，仓库[circle-of-friends](https://github.com/YanDao0313/circle-of-friends)，配置用的[yaml文件](https://raw.githubusercontent.com/YanDao0313/circle-of-friends/main/hexo_circle_of_friends/fc_settings.yaml) ，已确认GitHub令牌与Vercel令牌正确放行了对应的权限 

前端代码如下  
```html
<div class="post-container">
        <div class="post-detail gt-bg-theme-color-first">
            <article class="gt-post-content">
                <div id="hexo-circle-of-friends-root"></div>
                <script>
                    let UserConfig = {
                        private_api_url: 'https://cof-api.ydlk.cc/',
                        page_turning_number: 10,
                        error_img: 'https://sdn.geekzu.org/avatar/57d8260dfb55501c37dde588e7c3852c',
                        sort_rule: 'created'
                    }
                </script>
                <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zhheo/JS-Heo@master/mainColor/heoMainColor.css">-->
                <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/zhheo/JS-Heo@master/moments5/app.min.js"></script>
                <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/zhheo/JS-Heo@master/moments5/bundle.js"></script>
            </article>
        </div>
    </div>
```
> 前端代码参考自[张洪Heo](https://blog.zhheo.com/p/4e18a507.html)

**Comment by hiltay** [comment]
参考：https://vercel.com/docs/rest-api#endpoints/projects/retrieve-the-environment-variables-of-a-project-by-id-or-name
尝试使用`VERCEL_ACCESS_TOKEN`请求该api，看能否正常返回。

**Comment by YanDao0313** [comment]
返回`NOT_FOUND`
```json
{
    "error": {
        "code": "NOT_FOUND"
    }
}
```

**Comment by hiltay** [comment]
是该api的问题，排查一下即可。
比如`VERCEL_ACCESS_TOKEN`是否正确，项目名称是否正确。

**Comment by YanDao0313** [comment]
将请求调整为`https://api.vercel.com/v9/projects/c*************ds/env?teamId=team_B9*******************y9o`后就可以正常返回环境变量了，不知道是不是因为我部署到了团队账户上的原因
token给了完整的账户访问权限

**Comment by YanDao0313** [comment]
转移项目到个人账号后，可以直接通过GET`https://api.vercel.com/v9/projects/c*************ds/env`返回包含环境变量的json了，但是实际项目仍报错
```log
[POST] /login  15:15:51:88

[ERROR] AssertionError: 获取SECRET_KEY失败，error_code:404
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 297, in vc_handler
    response = asgi_cycle(__vc_module.app, body)
  File "/var/task/vc__handler__python.py", line 208, in __call__
    loop.run_until_complete(asgi_task)
  File "/var/lang/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/var/task/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/var/task/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/task/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/var/task/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/var/task/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/var/task/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/var/task/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/var/task/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/var/task/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/var/task/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/var/task/fastapi/routing.py", line 219, in app
    raw_response = await run_endpoint_function(
  File "/var/task/fastapi/routing.py", line 152, in run_endpoint_function
    return await dependant.call(**values)
  File "./api/main.py", line 163, in login
    return await login_(password.password)
  File "/var/task/api_dependencies/sql/sqlapi.py", line 298, in login_
    secret_key = await security.get_secret_key()
  File "/var/task/api_dependencies/sql/security.py", line 18, in get_secret_key
    res = await get_env(vercel_acces_token, project_name, env_name)
  File "/var/task/api_dependencies/utils/vercel_interface.py", line 33, in get_env
    assert response.status == 200, f"获取{env_name}失败，error_code:{response.status}"
```

**Comment by hiltay** [comment]
确认vercel的项目名称是否为`hexo-circle-of-friends`

**Comment by hiltay** [comment]
应该是改过名字`circle-of-friends`导致的。

**Comment by YanDao0313** [comment]
确实是vercel项目名与部署账号的问题，改了之后就好了😂
- [x] 重命名为 `hexo-circle-of-friends`
- [x] 从团队转移至个人账号

**Comment by hiltay** [comment]
目前vercel名称不能修改。后续版本可能会对这部分优化一下。

**Comment by YanDao0313** [comment]
感谢！
